# Generated by Django 3.0.2 on 2020-05-17 17:05

import accounts.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCalculators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.IntegerField(default=3000)),
                ('premium_package', models.BooleanField(default=True)),
                ('package_owner', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('file', models.CharField(blank=True, help_text='download link here!', max_length=300, null=True)),
                ('product_code', models.CharField(blank=True, max_length=10, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=accounts.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanCollectionPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.IntegerField(default=3000)),
                ('premium_package', models.BooleanField(default=True)),
                ('package_owner', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('product_code', models.CharField(blank=True, max_length=10, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=accounts.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.IntegerField(default=3000)),
                ('premium_package', models.BooleanField(default=True)),
                ('package_owner', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('product_code', models.CharField(blank=True, max_length=10, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=accounts.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
