# Generated by Django 3.0.2 on 2020-02-27 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minmarkets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanpackage',
            name='bought_by',
        ),
    ]
