# Generated by Django 3.0.2 on 2020-05-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minmarkets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loancalculators',
            options={'verbose_name': 'Loan Calculator', 'verbose_name_plural': 'Loan Calculators'},
        ),
    ]
