# Generated by Django 3.0.2 on 2020-12-05 17:38

import accounts.models
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minmarkets', '0002_auto_20200517_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerificationPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.IntegerField(default=3000)),
                ('premium_package', models.BooleanField(default=True)),
                ('package_owner', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('product_code', models.CharField(blank=True, max_length=10, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=accounts.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Featured Packages', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('featured_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minmarkets.LoanPackage')),
                ('featured_B', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minmarkets.LoanCalculators')),
                ('featured_C', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minmarkets.LoanCollectionPackage')),
                ('featured_D', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minmarkets.IdentityVerificationPackage')),
            ],
        ),
    ]
