# Generated by Django 3.0.2 on 2020-12-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minmarkets', '0003_featuredpackages_identityverificationpackage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredpackages',
            options={'verbose_name': 'Featured Package', 'verbose_name_plural': 'Featured Packages'},
        ),
    ]
