# Generated by Django 3.0.2 on 2020-12-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minmarkets', '0004_auto_20201205_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedPackages',
        ),
    ]
