# Generated by Django 3.0.2 on 2020-10-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_thirdpartycreds'),
        ('minone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minonedescription',
            name='users',
            field=models.ManyToManyField(blank=True, to='accounts.Profile'),
        ),
    ]
