# Generated by Django 3.0.2 on 2020-10-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minone', '0002_auto_20201012_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minonedescription',
            old_name='use_minone',
            new_name='maintenance_mode',
        ),
    ]
