# Generated by Django 3.0.2 on 2020-02-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
