# Generated by Django 3.0.2 on 2020-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincore', '0004_supporttickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('max_staff', models.PositiveIntegerField(blank=True, null=True)),
                ('maintenance_fee', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
            },
        ),
    ]
