# Generated by Django 3.0.2 on 2020-10-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcode',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
