# Generated by Django 3.0.2 on 2020-02-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmed_date',
        ),
    ]
