# Generated by Django 3.0.2 on 2020-10-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200517_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='duration_package',
            field=models.PositiveIntegerField(blank=True, help_text='Duration is recorded in months: 30days', null=True),
        ),
    ]
