# Generated by Django 3.0.2 on 2020-10-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_duration_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='duration_collection_package',
            field=models.PositiveIntegerField(blank=True, help_text='Duration is recorded in months: 30days', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pkg_collection_duration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pkg_duration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
