# Generated by Django 3.0.2 on 2020-02-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Customer', 'Customer')], max_length=20, null=True),
        ),
    ]
