# Generated by Django 3.0.2 on 2020-10-13 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201003_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyCreds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remita_dd_merchant', models.CharField(blank=True, max_length=300, null=True)),
                ('remita_dd_api_key', models.CharField(blank=True, max_length=300, null=True)),
                ('remita_dd_serviceType_id', models.CharField(blank=True, max_length=300, null=True)),
                ('remita_drf_merchant', models.CharField(blank=True, max_length=300, null=True)),
                ('remita_drf_api_key', models.CharField(blank=True, max_length=300, null=True)),
                ('remita_drf_api_token', models.CharField(blank=True, max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
