# Generated by Django 3.0.2 on 2020-10-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201013_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartycreds',
            name='remita_dd_api_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
