# Generated by Django 3.0.2 on 2020-02-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200209_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(blank=True, choices=[('FREEMIUM', 'FREEMIUM'), ('STARTUP', 'STARTUP'), ('BUSINESS', 'BUSINESS'), ('COMPANY', 'COMPANY'), ('ENTERPRISE', 'ENTERPRISE')], default='FREEMIUM', max_length=20, null=True),
        ),
    ]
