# Generated by Django 3.0.2 on 2020-11-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20201107_0151'),
        ('accounts', '0008_auto_20201106_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='BankAccountType',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserBankAccount',
        ),
    ]
