# Generated by Django 3.0.2 on 2020-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_staffs'),
        ('accounts', '0010_auto_20200222_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='keycode',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_for',
            field=models.ManyToManyField(to='company.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('phone', 'slug', 'keycode')},
        ),
    ]
