EMAIL_HOST = 'smtp-relay.sendinblue.com'
EMAIL_HOST_USER = 'support@minloans.com.ng'
EMAIL_HOST_PASSWORD = "J9PSXbz6mQhWK3OL"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "customer@minloans.com.ng"
SUPPORT_EMAIL = "support@minloans.com.ng"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "Minloans NG"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
SENDGRID_API_KEY = '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'
