EMAIL_HOST = 'smtp-relay.sendinblue.com'
EMAIL_HOST_USER = 'amjuuniquemfb@gmail.com'
EMAIL_HOST_PASSWORD = "DEwYVCnUMxLjzA49"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "support@gminloans.com.ng"
SUPPORT_EMAIL = "support@gminloans.com.ng"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "MINLOANS NG"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
SENDGRID_API_KEY = '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'