# Generated by Django 3.0.2 on 2020-06-16 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemitaCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantId', models.CharField(blank=True, max_length=200, null=True)),
                ('serviceTypeId', models.CharField(blank=True, max_length=200, null=True)),
                ('apiKey', models.CharField(blank=True, max_length=200, null=True)),
                ('mandateType', models.CharField(default='DD', max_length=100)),
                ('connected_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
