# Generated by Django 3.0.2 on 2020-02-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'branch', 'verbose_name_plural': 'branches'},
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
    ]
