# Generated by Django 3.0.2 on 2020-02-19 16:35

import accounts.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=accounts.models.upload_image_path),
        ),
    ]
