# Generated by Django 3.0.2 on 2020-06-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200619_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remitamandateactivationdata',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
