# Generated by Django 3.0.2 on 2020-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200222_1029'),
        ('company', '0005_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='staffs',
            field=models.ManyToManyField(related_name='workers', to='accounts.Profile'),
        ),
    ]
