# Generated by Django 3.0.2 on 2020-06-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200619_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remitamandateactivationdata',
            name='payer_bank_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
