# Generated by Django 3.0.2 on 2020-10-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_remove_loantype_duration'),
        ('company', '0008_auto_20200620_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remitamandateactivationdata',
            name='connected_firm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='remitamandateactivationdata',
            name='loan_key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Loan'),
        ),
    ]
