# Generated by Django 3.0.2 on 2020-10-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20201017_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitamandateactivationdata',
            name='remitaTransRef',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
