# Generated by Django 3.0.2 on 2020-10-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20201027_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitamandateactivationdata',
            name='amount_debited_at_instance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='remitamandateactivationdata',
            name='lastStatusUpdateTime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
