# Generated by Django 3.0.2 on 2020-10-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20201028_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitamandateactivationdata',
            name='mandate_requestId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
