# Generated by Django 3.0.2 on 2020-10-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_remove_loantype_duration'),
        ('company', '0014_remitamandateactivationdata_mandate_requestid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemitaPaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('lastStatusUpdateTime', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('statuscode', models.CharField(blank=True, max_length=100, null=True)),
                ('RRR', models.CharField(blank=True, max_length=100, null=True)),
                ('transactionRef', models.CharField(blank=True, max_length=100, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='RemitaMandateTransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_transaction_count', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
                ('payment_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.RemitaPaymentDetails')),
                ('remita_dd_mandate_owned_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.RemitaMandateActivationData')),
            ],
        ),
    ]
