# Generated by Django 3.0.2 on 2020-10-30 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_remitamandatetransactionrecord_remitapaymentdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remitamandatetransactionrecord',
            options={'verbose_name': 'Remita Mandate Transaction Record', 'verbose_name_plural': 'Remita Mandate Transaction Record'},
        ),
        migrations.AlterModelOptions(
            name='remitapaymentdetails',
            options={'verbose_name': 'Remita Payment Details', 'verbose_name_plural': 'Remita Payment Details'},
        ),
        migrations.RemoveField(
            model_name='remitamandatetransactionrecord',
            name='payment_details',
        ),
        migrations.AddField(
            model_name='remitapaymentdetails',
            name='remita_transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.RemitaMandateTransactionRecord'),
        ),
    ]
