# Generated by Django 3.0.2 on 2020-11-01 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_remove_loantype_duration'),
        ('company', '0016_auto_20201029_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemitaMandateStatusReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mandate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.CharField(blank=True, help_text='Mandate Registered On: ', max_length=100, null=True)),
                ('mandate_status', models.BooleanField(default=True)),
                ('report_status', models.CharField(blank=True, max_length=100, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
            ],
            options={
                'verbose_name': 'Remita Mandate Status Report',
                'verbose_name_plural': 'Remita Mandate Status Reports',
            },
        ),
    ]
