# Generated by Django 3.0.2 on 2020-11-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_bankaccounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
