# Generated by Django 3.0.2 on 2020-11-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_bankaccounttype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
