# Generated by Django 3.0.2 on 2020-02-26 15:00

import accounts.models
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0006_company_staffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('registered_date', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Deposited In Branch', 'Deposited In Branch'), ('Collateral With Borrower', 'Collateral With Borrower'), ('Returned To Borrower', 'Returned To Borrower'), ('Sold', 'Sold'), ('Lost', 'Lost')], default='OPEN', max_length=40, null=True)),
                ('value', models.CharField(blank=True, help_text='Object Worth', max_length=300, null=True)),
                ('condition', models.TextField(help_text='Describe status of object')),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=accounts.models.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='CollateralFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=accounts.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollateralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_key', models.CharField(blank=True, max_length=300, null=True)),
                ('loan_activator_fee', models.CharField(blank=True, max_length=300, null=True)),
                ('principal_amount', models.CharField(blank=True, max_length=300, null=True)),
                ('balance_due', models.CharField(blank=True, max_length=300, null=True)),
                ('interest', models.CharField(blank=True, choices=[('Per Year', 'Per Year'), ('Per Month', 'Per Month'), ('Per Week', 'Per Week'), ('Per Day', 'Per Day')], default='Per Month', max_length=20, null=True)),
                ('loan_duration_circle', models.CharField(blank=True, choices=[('Per Year', 'Per Year'), ('Per Month', 'Per Month'), ('Per Week', 'Per Week'), ('Per Day', 'Per Day')], default='Per Month', max_length=20, null=True)),
                ('loan_duration_circle_figure', models.IntegerField(default=1)),
                ('repayment_circle', models.CharField(blank=True, choices=[('Per Year', 'Per Year'), ('Per Month', 'Per Month'), ('Per Week', 'Per Week'), ('Per Day', 'Per Day')], default='Per Month', max_length=20, null=True)),
                ('number_repayments', models.CharField(blank=True, max_length=300, null=True)),
                ('release_date', models.DateTimeField(help_text='Loan Paid To Customer On:')),
                ('collection_date', models.DateTimeField(help_text='Each Date Loan Balance Is Been Paid Back')),
                ('end_date', models.DateTimeField(help_text='Maturity Date')),
                ('processing_fee', models.CharField(blank=True, max_length=300, null=True)),
                ('grace_period', models.IntegerField(default=1, help_text='Counts In Days')),
                ('insurance', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('loan_file_upload', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=accounts.models.upload_image_path)),
                ('active', models.BooleanField(default=True)),
                ('loan_status', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('PARTIAL', 'PARTIAL'), ('CLOSED', 'CLOSED'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'db_table': 'loan',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='LoanTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeOfRepayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('describe', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('describe', models.TextField()),
                ('punishment_fee', models.CharField(blank=True, max_length=300, null=True)),
                ('reoccuring', models.BooleanField(verbose_name=False)),
                ('value_on_period', models.IntegerField(blank=True, default=7, null=True)),
                ('period', models.CharField(blank=True, choices=[('Per Year', 'Per Year'), ('Per Month', 'Per Month'), ('Per Week', 'Per Week'), ('Per Day', 'Per Day')], default='Per Month', max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
