# Generated by Django 3.0.2 on 2020-02-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0006_company_staffs'),
        ('loans', '0001_initial'),
        ('borrowers', '0001_initial'),
        ('minmarkets', '0001_initial'),
        ('accounts', '0010_auto_20200222_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='minmarkets.LoanPackage'),
        ),
        migrations.AddField(
            model_name='loanterms',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='loanterms',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minmarkets.LoanPackage'),
        ),
        migrations.AddField(
            model_name='loan',
            name='account_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowers.Borrower'),
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Collateral'),
        ),
        migrations.AddField(
            model_name='loan',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_terms',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.LoanTerms'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.LoanType'),
        ),
        migrations.AddField(
            model_name='loan',
            name='mode_of_repayments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.ModeOfRepayments'),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Penalty'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='collateral_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.CollateralFiles'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='collateral_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.CollateralType'),
        ),
    ]
