# Generated by Django 3.0.2 on 2020-06-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20200518_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='collection_date',
            field=models.DateTimeField(blank=True, help_text='Date User Collects The Loan Money', null=True),
        ),
    ]
