# Generated by Django 3.0.2 on 2020-07-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20200617_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateralfiles',
            name='file_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='collateralfiles',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
