# Generated by Django 3.0.2 on 2020-02-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loantype_bought_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_activator_fee',
        ),
    ]
