# Generated by Django 3.0.2 on 2020-02-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loan_loan_activator_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collateral',
            options={'verbose_name': 'Collateral', 'verbose_name_plural': 'Collateral'},
        ),
        migrations.AlterModelOptions(
            name='collateralfiles',
            options={'verbose_name': 'Collateral File', 'verbose_name_plural': 'Collateral Files'},
        ),
        migrations.AlterModelOptions(
            name='collateraltype',
            options={'verbose_name': 'Collateral Type', 'verbose_name_plural': 'Collateral Type'},
        ),
        migrations.AlterModelOptions(
            name='loanterms',
            options={'verbose_name': 'Loan Terms', 'verbose_name_plural': 'Loan Terms'},
        ),
        migrations.AlterModelOptions(
            name='loantype',
            options={'verbose_name': 'Loan Type', 'verbose_name_plural': 'Loan Type'},
        ),
        migrations.AlterModelOptions(
            name='modeofrepayments',
            options={'verbose_name': 'Mode Of Repayment', 'verbose_name_plural': 'Mode Of Repayments'},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'verbose_name': 'Penalty', 'verbose_name_plural': 'Penalties'},
        ),
        migrations.RenameField(
            model_name='penalty',
            old_name='reoccuring',
            new_name='re_occuring',
        ),
        migrations.AddField(
            model_name='collateral',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
