# Generated by Django 3.0.2 on 2020-07-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20200712_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='view_shader',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
