# Generated by Django 3.0.2 on 2020-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20200228_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_duration_circle',
            field=models.CharField(blank=True, choices=[('Years', 'Years'), ('Months', 'Months'), ('Weeks', 'Weeks'), ('Days', 'Days')], default='Months', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_circle',
            field=models.CharField(blank=True, choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Daily', 'Daily')], default='Monthly', max_length=20, null=True),
        ),
    ]
