# Generated by Django 3.0.2 on 2020-07-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_collateral_view_shader'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='registered_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
