# Generated by Django 3.0.2 on 2020-03-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_auto_20200228_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_period',
            field=models.CharField(blank=True, choices=[('Per Year', 'Per Year'), ('Per Month', 'Per Month'), ('Per Week', 'Per Week'), ('Per Day', 'Per Day')], default='Per Month', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
