# Generated by Django 3.0.2 on 2020-09-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200517_1005'),
        ('loans', '0006_collateral_registered_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanActivityComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_to', to='accounts.Profile')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_done_by', to='accounts.Profile')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
            ],
            options={
                'verbose_name': 'loan activity comments',
                'verbose_name_plural': 'loan activity comments',
                'db_table': 'loan activity comments',
                'ordering': ('-timestamp',),
            },
        ),
    ]
