# Generated by Django 3.0.2 on 2020-10-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loanactivitycomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
