# Generated by Django 3.0.2 on 2020-03-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_auto_20200311_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='condition',
            field=models.TextField(blank=True, help_text='Describe status of object', null=True),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='registered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='collection_date',
            field=models.DateTimeField(blank=True, help_text='Each Date Loan Balance Is Been Paid Back', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Maturity Date', null=True),
        ),
        migrations.AlterField(
            model_name='loanterms',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modeofrepayments',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
