# Generated by Django 3.0.2 on 2020-10-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loantype_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantype',
            name='duration',
        ),
    ]
