# Generated by Django 3.0.2 on 2020-11-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_remove_loantype_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateraltype',
            name='owned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Loan'),
        ),
    ]
