# Generated by Django 3.0.2 on 2020-11-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_auto_20201102_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='linked_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_loan', to='loans.Loan'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_penalty', to='loans.Penalty'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='re_occuring',
            field=models.BooleanField(default=True),
        ),
    ]
