# Generated by Django 3.0.2 on 2020-11-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0010_borrowergroup_color_code'),
        ('loans', '0013_auto_20201103_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowers.BorrowerGroup'),
        ),
    ]
