# Generated by Django 3.0.2 on 2021-04-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0010_borrowergroup_color_code'),
        ('banks', '0002_bankcode_otp_enabled'),
        ('loans', '0015_auto_20201116_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRFSalaryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_data', models.BooleanField(default=False)),
                ('response_id', models.CharField(blank=True, max_length=299, null=True)),
                ('count', models.IntegerField(default=0)),
                ('customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=200, null=True)),
                ('bvn', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('first_payment_date', models.DateTimeField()),
                ('bank_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.BankCode')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowers.Borrower')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
            ],
            options={
                'verbose_name': 'DRF Salary History',
                'verbose_name_plural': 'DRF Salary History',
                'db_table': 'DRF Salary History',
            },
        ),
        migrations.CreateModel(
            name='DRFSalaryPaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.BankCode')),
                ('drf_salary_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.DRFSalaryHistory')),
            ],
            options={
                'verbose_name': 'DRF Payment Details',
                'verbose_name_plural': 'DRF Payment Details',
                'db_table': 'DRF Payment Details',
            },
        ),
    ]
