# Generated by Django 3.0.2 on 2021-04-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_drfsalaryhistory_drfsalarypaymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drfsalaryhistory',
            name='loan',
        ),
    ]
