# Generated by Django 3.0.2 on 2021-04-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_remove_drfsalaryhistory_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drfsalaryhistory',
            name='first_payment_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
