# Generated by Django 3.0.2 on 2021-04-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_auto_20210427_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drfsalarypaymentdetails',
            old_name='account_number',
            new_name='payment_details',
        ),
        migrations.RemoveField(
            model_name='drfsalarypaymentdetails',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='drfsalarypaymentdetails',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='drfsalarypaymentdetails',
            name='payment_date',
        ),
    ]
