# Generated by Django 3.0.2 on 2021-04-30 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_bankaccounttype_color_code'),
        ('loans', '0019_auto_20210427_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonoUserResponseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mono_connect_code', models.CharField(blank=True, max_length=300, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'verbose_name': 'Mono User Code',
                'verbose_name_plural': 'Mono Users Code',
                'db_table': 'Mono Connect User Code',
            },
        ),
    ]
