# Generated by Django 3.0.2 on 2021-05-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bankcode_otp_enabled'),
        ('loans', '0021_loanrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRFDisbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_data', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('response_id', models.CharField(blank=True, max_length=299, null=True)),
                ('request_date', models.CharField(blank=True, max_length=299, null=True)),
                ('response_date', models.CharField(blank=True, max_length=299, null=True)),
                ('response_code', models.CharField(blank=True, max_length=299, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('authorisation_code', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('mandate_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.BankCode')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
            ],
            options={
                'verbose_name': 'DRF Disbursement',
                'verbose_name_plural': 'DRF Disbursements',
                'db_table': 'DRF Disbursement',
            },
        ),
    ]
