# Generated by Django 3.0.2 on 2021-05-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0017_borrowerfrommono'),
        ('loans', '0022_drfdisbursement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequests',
            name='borrower',
        ),
        migrations.AddField(
            model_name='loanrequests',
            name='borrower_mono_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowers.BorrowerFromMono'),
        ),
    ]
