# Generated by Django 3.0.2 on 2020-05-17 17:05

import accounts.models
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=accounts.models.upload_image_path)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('address', models.CharField(blank=True, help_text='Block 32, Arizona Street', max_length=300, null=True)),
                ('lga', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, choices=[('Lagos', 'Lagos'), ('Kano', 'Kano'), ('Enugu', 'Enugu')], help_text='Province/State', max_length=300, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('land_line', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('business_name', models.CharField(blank=True, max_length=300, null=True)),
                ('working_status', models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Self-Employed', 'Self-Employed')], max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('unique_identifier', models.CharField(blank=True, help_text='Social Security Number, License Or Registration ID', max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=11, null=True)),
                ('bvn', models.CharField(blank=True, help_text='Bank Verification Number', max_length=300, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.BankCode')),
                ('registered_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'unique_together': {('slug', 'phone', 'email')},
            },
        ),
        migrations.CreateModel(
            name='BorrowerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('meeting_schedule', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('borrowers', models.ManyToManyField(related_name='members', to='borrowers.Borrower')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowers.Borrower')),
                ('group_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_leader', to='borrowers.Borrower')),
                ('registered_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'unique_together': {('slug', 'name')},
            },
        ),
    ]
