# Generated by Django 3.0.2 on 2020-07-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
