# Generated by Django 3.0.2 on 2020-02-28 13:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0002_auto_20200228_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowergroup',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='land_line',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterUniqueTogether(
            name='borrowergroup',
            unique_together={('slug', 'name')},
        ),
    ]
