# Generated by Django 3.0.2 on 2020-02-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_staffs'),
        ('borrowers', '0003_auto_20200228_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowergroup',
            name='registered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
