# Generated by Django 3.0.2 on 2020-07-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_auto_20200725_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='address',
            field=models.CharField(blank=True, help_text='Block 32, Arizona Street', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='bvn',
            field=models.CharField(blank=True, help_text='Bank Verification Number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='lga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='state',
            field=models.CharField(blank=True, choices=[('Lagos', 'Lagos'), ('Kano', 'Kano'), ('Enugu', 'Enugu')], help_text='Province/State', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='unique_identifier',
            field=models.CharField(blank=True, help_text='Social Security Number, License Or Registration ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='working_status',
            field=models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Self-Employed', 'Self-Employed')], max_length=255, null=True),
        ),
    ]
