# Generated by Django 3.0.2 on 2020-03-07 18:50

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0004_borrowergroup_registered_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
