# Generated by Django 3.0.2 on 2020-07-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0004_auto_20200728_0117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrower',
            unique_together=set(),
        ),
    ]
