# Generated by Django 3.0.2 on 2020-03-07 18:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0005_auto_20200307_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
