# Generated by Django 3.0.2 on 2020-11-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0006_borrowerbankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowerbankaccount',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='borrowerbankaccount',
            name='gender',
        ),
    ]
