# Generated by Django 3.0.2 on 2020-11-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0009_auto_20201116_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowergroup',
            name='color_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
