# Generated by Django 3.0.2 on 2021-05-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0010_borrowergroup_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='account_balance_on_commercial_bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
