# Generated by Django 3.0.2 on 2021-05-11 22:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0015_auto_20210511_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='Nigeria', max_length=2, null=True),
        ),
    ]
