# Generated by Django 3.0.2 on 2021-05-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_bankaccounttype_color_code'),
        ('borrowers', '0016_auto_20210511_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerFromMono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(blank=True, max_length=300, null=True)),
                ('bvn', models.CharField(blank=True, max_length=300, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=300, null=True)),
                ('home_address', models.CharField(blank=True, max_length=300, null=True)),
                ('office_address', models.CharField(blank=True, max_length=300, null=True)),
                ('mono_id', models.CharField(blank=True, max_length=300, null=True)),
                ('bank', models.CharField(blank=True, max_length=300, null=True)),
                ('account_number', models.CharField(blank=True, max_length=300, null=True)),
                ('account_type', models.CharField(blank=True, max_length=300, null=True)),
                ('currency', models.CharField(blank=True, max_length=300, null=True)),
                ('balance_in_kobo', models.CharField(blank=True, max_length=300, null=True)),
                ('registered_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
